name: CI

on:
  pull_request:
    branches:
      - develop
      - test
      - stage
      - main
  push:
    branches:
      - develop
      - test
      - stage
      - main
permissions:
  contents: read

jobs:
  backend:
    name: Backend checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      NODE_ENV: test
      PORT: 3001
      FRONTEND_URL: http://localhost:5173
      AUTH0_DOMAIN: test-domain.example.com
      AUTH0_AUDIENCE: https://api.test.example.com
      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/auth0_fullstack_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck backend
        run: npm run typecheck

      - name: Unit test backend
        run: npm run test:unit

      - name: Integration test backedn
        run: npm run test:integration

      - name: Build backend
        run: npm run build

  frontend:
    name: Frontend Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    env:
      VITE_APP_ENV: test
      VITE_API_BASE_URL: http://localhost:3001
      VITE_AUTH0_DOMAIN: test-domain.example.com
      VITE_AUTH0_CLIENT_ID: test-client-id
      VITE_AUTH0_AUDIENCE: https://api.test.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck frontend
        run: npm run typecheck

      - name: Unit test frontend
        run: npm run test:unit

      - name: Build frontend
        run: npm run build
